[package]
name = "arcana"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
csv = "1"
viuer = { version = "0.9.2", features = ["print-file"] }
image = "0.25"
imageproc = "0.25.0"

[[bin]]
name = "arcana"
path = "src/main.rs"
